// <auto-generated />
using System;
using CRUD_DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUD_DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220921065623_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUD_DAL.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10e06c31-0e5d-4a81-b52f-7435a84ddbda"),
                            BirthDate = new DateTime(2022, 9, 21, 9, 56, 22, 959, DateTimeKind.Local).AddTicks(740),
                            JobTitle = "A1",
                            MobilePhone = "+375(33)2345678",
                            Name = "Dima"
                        },
                        new
                        {
                            Id = new Guid("68eab7c2-b0df-4ef8-a147-98b327372a7e"),
                            BirthDate = new DateTime(2022, 9, 21, 9, 56, 22, 960, DateTimeKind.Local).AddTicks(34),
                            JobTitle = "Global",
                            MobilePhone = "+375(44)2345678",
                            Name = "Roma"
                        },
                        new
                        {
                            Id = new Guid("52d095f2-49f5-4ebb-be36-4541d92b90ef"),
                            BirthDate = new DateTime(2022, 9, 21, 9, 56, 22, 960, DateTimeKind.Local).AddTicks(53),
                            JobTitle = "MTC",
                            MobilePhone = "+375(29)2345678",
                            Name = "Pasha"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
